# Generated by Django 2.1.7 on 2019-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190318_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
