# Generated by Django 2.1.5 on 2019-03-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190321_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='message',
            new_name='filename',
        ),
    ]
