# Generated by Django 2.1.7 on 2019-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20190401_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='datafile',
            field=models.FileField(blank=True, upload_to='STL'),
        ),
    ]
