# Generated by Django 2.1.7 on 2019-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='datafile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
