# Generated by Django 2.1.7 on 2019-04-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20190401_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
