# Generated by Django 2.1.5 on 2019-04-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190401_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='datafile',
        ),
    ]
